AWSTemplateFormatVersion: 2010-09-09
Description: Stealth Store Lambda functions

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  services:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/services.servicesHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      MemorySize: 128
      Timeout: 100
      Description: Define all available services offered at the Stealth Store.
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers/services.ts
